name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  
  build:
    runs-on: ubuntu-latest
    container: jqueen/msp430-builds-public

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    
    - name: Build Code
      run: make -f makefile.docker
      

